/*******************************************************************************
   Create database
********************************************************************************/
CREATE TABLE ERS_REIMBURSEMENT_STATUS(
REIMB_STATUS_ID NUMBER NOT NULL,
REIMB_STATUS VARCHAR2(10),
PRIMARY KEY (REIMB_STATUS_ID) 
);
CREATE TABLE ERS_REIMBURSEMENT_TYPE(
REIMB_TYPE_ID NUMBER,
REIMB_TYPE VARCHAR2(10),
PRIMARY KEY (REIMB_TYPE_ID)
);
CREATE TABLE ERS_USER_ROLES(
ERS_USER_ROLE_ID NUMBER,
USER_ROLE VARCHAR2(10),
PRIMARY KEY (ERS_USER_ROLE_ID)
);
CREATE TABLE ERS_USERS(
ERS_USERS_ID NUMBER,
ERS_USERNAME VARCHAR2(50) UNIQUE,
ERS_PASSWORD VARCHAR2(50),
USER_FIRST_NAME VARCHAR2(100),
USER_LAST_NAME VARCHAR2(100),
USER_EMAIL VARCHAR2(150) UNIQUE,
USER_ROLE_ID NUMBER,
PRIMARY KEY (ERS_USERS_ID),
FOREIGN KEY (USER_ROLE_ID) REFERENCES ERS_USER_ROLES(ERS_USER_ROLE_ID)
);
CREATE TABLE ERS_REIMBURSEMENT(
REIMB_ID NUMBER,
REIMB_AMOUNT NUMBER,
REIM_SUBMITTED TIMESTAMP,
REIMB_RESOLVED TIMESTAMP,
REIMB_DESCRIPTION VARCHAR2(250),
REIMB_RECEIPT BLOB,
REIMB_AUTHOR NUMBER,
REIMB_RESOLVER NUMBER,
REIMB_STATUS_ID NUMBER,
REIMB_TYPE_ID NUMBER,
PRIMARY KEY (REIMB_ID),
FOREIGN KEY (REIMB_AUTHOR) REFERENCES ERS_USERS(ERS_USERS_ID),
FOREIGN KEY (REIMB_RESOLVER) REFERENCES ERS_USERS(ERS_USERS_ID),
FOREIGN KEY (REIMB_STATUS_ID) REFERENCES ERS_REIMBURSEMENT_STATUS(REIMB_STATUS_ID),
FOREIGN KEY (REIMB_TYPE_ID) REFERENCES ERS_REIMBURSEMENT_TYPE(REIMB_TYPE_ID)
);


/*******************************************************************************
   Create Sequence
********************************************************************************/
CREATE SEQUENCE USERID_SEQ;
CREATE SEQUENCE REIMBURSEMENT_SEQ;


/*******************************************************************************
   Create Triggers
********************************************************************************/
CREATE OR REPLACE TRIGGER ADD_REIMBURSEMENT
BEFORE INSERT ON ERS_REIMBURSEMENT
FOR EACH ROW
BEGIN
SELECT REIMBURSEMENT_SEQ.NEXTVAL INTO :NEW.REIMB_ID FROM DUAL;
END;
/


CREATE OR REPLACE TRIGGER ADD_USER
BEFORE INSERT ON ERS_USERS
FOR EACH ROW
BEGIN
SELECT USERID_SEQ.NEXTVAL INTO :NEW.ERS_USERS_ID FROM DUAL;
END;
/

/*******************************************************************************
   Create Procedure
********************************************************************************/
CREATE OR REPLACE PROCEDURE GET_ALL_STATUS 
(STATUS_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN
OPEN STATUS_CURSOR FOR SELECT * FROM ERS_REIMBURSEMENT_STATUS;
END;
/

/*******************************************************************************
   Populate Tables
********************************************************************************/
INSERT INTO ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID, REIMB_STATUS) VALUES (0,'denied');
INSERT INTO ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID, REIMB_STATUS) VALUES (1,'pending');
INSERT INTO ERS_REIMBURSEMENT_STATUS (REIMB_STATUS_ID, REIMB_STATUS) VALUES (2,'accepted');
COMMIT;

INSERT INTO ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID, REIMB_TYPE) VALUES (1,'LODGING');
INSERT INTO ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID, REIMB_TYPE) VALUES (2,'TRAVEL');
INSERT INTO ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID, REIMB_TYPE) VALUES (3,'FOOD');
INSERT INTO ERS_REIMBURSEMENT_TYPE (REIMB_TYPE_ID, REIMB_TYPE) VALUES (4,'OTHER');
COMMIT;

INSERT INTO ERS_USER_ROLES (ERS_USER_ROLE_ID, USER_ROLE) VALUES (1,'EMPLOYEE');
INSERT INTO ERS_USER_ROLES (ERS_USER_ROLE_ID, USER_ROLE) VALUES (2,'MANAGER');
COMMIT;

INSERT INTO ERS_USERS (ERS_USERNAME,ERS_PASSWORD,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_ROLE_ID) VALUES ('test','test','test','test','test',1);
INSERT INTO ERS_USERS (ERS_USERNAME,ERS_PASSWORD,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_ROLE_ID) VALUES ('gr','pass','gr','gr','gr@gmail.com',1);
INSERT INTO ERS_USERS (ERS_USERNAME,ERS_PASSWORD,USER_FIRST_NAME,USER_LAST_NAME,USER_EMAIL,USER_ROLE_ID) VALUES ('admin','pass','admin','admin','email@gmail.com',2);
COMMIT;

INSERT INTO ERS_REIMBURSEMENT 
(REIMB_ID, REIMB_AMOUNT, REIM_SUBMITTED, REIMB_RESOLVED,REIMB_DESCRIPTION,REIMB_RECEIPT, REIMB_AUTHOR, REIMB_RESOLVER, REIMB_STATUS_ID, REIMB_TYPE_ID)
VALUES (1,12,NULL,NULL,'IN PROGRESS',NULL,1,1,1,1);
COMMIT;
INSERT INTO ERS_REIMBURSEMENT 
(REIMB_ID, REIMB_AMOUNT, REIMB_AUTHOR, REIMB_STATUS_ID, REIMB_TYPE_ID)
VALUES(6,200,2,1,1);
COMMIT;

/*******************************************************************************
   Testing
********************************************************************************/

SELECT * FROM ERS_REIMBURSEMENT_STATUS;
SELECT * FROM ERS_REIMBURSEMENT_TYPE;
SELECT * FROM ERS_USER_ROLES;
SELECT * FROM ERS_USERS;
SELECT * FROM ERS_REIMBURSEMENT;



/*******************************************************************************
   Drop Tables
********************************************************************************/
DROP TABLE ERS_REIMBURSEMENT_STATUS;
DROP TABLE ERS_REIMBURSEMENT_TYPE;
DROP TABLE ERS_USER_ROLES;
DROP TABLE ERS_USERS;
DROP TABLE ERS_REIMBURSEMENT;

/*******************************************************************************
   Drop Sequences
********************************************************************************/
DROP SEQUENCE USERID_SEQ;
DROP SEQUENCE REIMBURSEMENT_SEQ;